name: Run Telegram Bot

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create data directory
      run: mkdir -p data
    
    - name: Debug Environment
      run: |
        echo "Python version:"
        python --version
        echo "Checking for token (safely):"
        if [ -n "$TELEGRAM_BOT_TOKEN" ]; then
          echo "Token is set"
        else
          echo "Token is NOT set"
        fi
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    
    - name: Run bot
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      run: python bot.py

    # Optional: Save data as artifact
    - uses: actions/upload-artifact@main
      if: always()
      with:
        name: bot-data
        path: data/
        retention-days: 1
